In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# !pip install seaborn

In [3]:
np.array([4,5,6,8,9,12,11])

array([ 4,  5,  6,  8,  9, 12, 11])

In [4]:
np.array([5,6,2,4,9,'hi'])

array(['5', '6', '2', '4', '9', 'hi'], dtype='<U11')

In [5]:
np.array([4,5,7,8,2,True,10.45])

array([ 4.  ,  5.  ,  7.  ,  8.  ,  2.  ,  1.  , 10.45])

In [6]:
np.array([[5,4,3,7],[9,8,3,5],[1,4,7,2]])

array([[5, 4, 3, 7],
       [9, 8, 3, 5],
       [1, 4, 7, 2]])

In [7]:
x = np.array([[5,4,3,7],[9,8,3,5],[1,4,7,2]])

In [8]:
x.shape

(3, 4)

In [11]:
x.ndim

2

In [12]:
print(x)

[[5 4 3 7]
 [9 8 3 5]
 [1 4 7 2]]


In [13]:
x[0]

array([5, 4, 3, 7])

In [14]:
x[0:2]

array([[5, 4, 3, 7],
       [9, 8, 3, 5]])

In [15]:
x[0][0]

5

In [17]:
x[0:2,0:2]

array([[5, 4],
       [9, 8]])

In [18]:
x[:,0:2]

array([[5, 4],
       [9, 8],
       [1, 4]])

In [20]:
x[:,0:1]

array([[5],
       [9],
       [1]])

In [21]:
# will return a random number b/w 0 and 1
np.random.random()

0.4540225399429719

In [23]:
np.random.random([3,5])

array([[0.71736055, 0.78719617, 0.68521002, 0.30114487, 0.86120045],
       [0.76852548, 0.58148583, 0.1025491 , 0.89263816, 0.52310852],
       [0.41370073, 0.74006851, 0.06355488, 0.52641067, 0.65187201]])

In [24]:
np.random.randint(1,10)

3

In [25]:
np.random.randint(1,20,5)

array([ 1, 19,  5,  6, 18])

In [26]:
np.random.randint(1,20,(5,5))

array([[ 8,  1,  3, 11, 14],
       [ 3,  1, 13, 11, 19],
       [13,  3,  8, 18, 16],
       [13, 10, 15, 14,  6],
       [12,  6,  8, 13, 14]])

In [27]:
x = np.random.randint(1,20,(5,5))

In [30]:
y = np.array([[3,5,6,8,2]])

In [31]:
y

array([[3, 5, 6, 8, 2]])

In [32]:
# append data row wise
np.concatenate([x,y])

array([[12, 13, 13, 16, 10],
       [14, 12, 15,  4,  2],
       [ 2, 14, 11, 19, 13],
       [10, 10, 16,  6,  4],
       [17, 16, 18, 18,  5],
       [ 3,  5,  6,  8,  2]])

In [41]:
y2 = np.array([[5],[6],[2],[6],[7]])

In [42]:
y2

array([[5],
       [6],
       [2],
       [6],
       [7]])

In [43]:
y2.shape

(5, 1)

In [44]:
x.shape

(5, 5)

In [45]:
# append data column wise
np.c_[x,y2]

array([[12, 13, 13, 16, 10,  5],
       [14, 12, 15,  4,  2,  6],
       [ 2, 14, 11, 19, 13,  2],
       [10, 10, 16,  6,  4,  6],
       [17, 16, 18, 18,  5,  7]])