In [1]:
import numpy as np

In [88]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y=np.array([[1],[1],[0]])

In [89]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [90]:
y

array([[1],
       [1],
       [0]])

In [91]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [92]:
def derivativeSigmoid(x):
    return x * (1 - x)

In [93]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1
epochs = 100000
learning_rate = 0.01

In [94]:
wh = np.random.random(size=(input_neurons,hidden_neurons))
bh = np.random.random(size=(1,hidden_neurons))
wout = np.random.random(size=(hidden_neurons,output_neurons))
bout = np.random.random(size=(1,output_neurons))

In [95]:
for i in range(epochs):
    # feedforward
    z1 = np.dot(X,wh) + bh
    hiddenlayer = sigmoid(z1)
    z2 = np.dot(hiddenlayer,wout) + bout
    outputlayer = sigmoid(z2)
    
    # backpropagation
    error = y - outputlayer
    slopeOutputLayer = derivativeSigmoid(outputlayer)
    slopeHiddenLayer = derivativeSigmoid(hiddenlayer)
    
    delta_output = error * slopeOutputLayer
    errorHiddenLayer = np.dot(delta_output,wout.T)
    delta_hidden = errorHiddenLayer * slopeHiddenLayer
    
    wout += hiddenlayer.T.dot(delta_output) * learning_rate
    bout += np.sum(delta_output, axis=0, keepdims=True) * learning_rate
    wh += X.T.dot(delta_hidden) * learning_rate
    bh += np.sum(delta_hidden) * learning_rate

In [32]:
# z1 = np.dot(X,wh) + bh

In [33]:
# z1.shape

In [34]:
# hiddenlayer = sigmoid(z1)

In [16]:
# hiddenlayer

array([[0.14320625, 0.29201317, 0.20298874],
       [0.0911637 , 0.24054945, 0.12326581],
       [0.18048125, 0.29254332, 0.12610895]])

In [17]:
# z2 = np.dot(hiddenlayer,wout) + bout

In [18]:
# z2

array([[1.10175504],
       [1.03896667],
       [1.08291715]])

In [19]:
# outputlayer = sigmoid(z2)

In [20]:
# outputlayer

array([[0.2494112 ],
       [0.26134942],
       [0.25295437]])

In [22]:
# error = outputlayer - y
# slopeOutputLayer = derivativeSigmoid(outputlayer)
# slopeHiddenLayer = derivativeSigmoid(hiddenlayer)

In [23]:
# error

array([[-0.7505888 ],
       [-0.73865058],
       [ 0.25295437]])

In [24]:
# slopeHiddenLayer

array([[0.12269822, 0.20674148, 0.16178431],
       [0.08285288, 0.18268541, 0.10807135],
       [0.14790777, 0.20696173, 0.11020548]])

In [25]:
# slopeOutputLayer

array([[0.18720525],
       [0.1930459 ],
       [0.18896846]])

In [26]:
# delta_output = error * slopeOutputLayer

In [27]:
# delta_output

array([[-0.14051417],
       [-0.14259347],
       [ 0.0478004 ]])

In [29]:
# errorHiddenLayer = np.dot(delta_output.T,wout)

In [96]:
outputlayer

array([[0.98937903],
       [0.98276609],
       [0.02298118]])